// Storefront catalogue data. The products below are shown until the live
// catalogue arrives from /api/products (and if it cannot be reached).

export const CROPS = [
  { id: 'all', name: 'All Crops', icon: 'fa-wheat-awn' },
  { id: 'Paddy/Rice', name: 'Paddy / Rice', icon: 'fa-seedling' },
  { id: 'Wheat', name: 'Wheat', icon: 'fa-wheat-awn' },
  { id: 'Cotton', name: 'Cotton', icon: 'fa-cloud' },
  { id: 'Tomato', name: 'Tomato', icon: 'fa-apple-whole' },
  { id: 'Corn', name: 'Corn / Maize', icon: 'fa-plant-wilt' },
  { id: 'Sugarcane', name: 'Sugarcane', icon: 'fa-cubes-stacked' },
  { id: 'Citrus', name: 'Citrus / Fruits', icon: 'fa-lemon' },
  { id: 'Grapes', name: 'Grapes', icon: 'fa-wine-glass-empty' },
  { id: 'Potato', name: 'Potato', icon: 'fa-circle-dot' },
]

export const DISEASES = [
  { id: 'all', name: 'All Diseases & Pests' },
  { id: 'Blast', name: 'Rice Blast & Sheath Blight' },
  { id: 'Blight', name: 'Early / Late Blight' },
  { id: 'Rust', name: 'Leaf Rust & Stripe Rust' },
  { id: 'Aphids', name: 'Aphids & Jassids' },
  { id: 'Whitefly', name: 'Whitefly & Thrips' },
  { id: 'Downy Mildew', name: 'Downy & Powdery Mildew' },
  { id: 'Caterpillars', name: 'Fruit Borer & Caterpillars' },
  { id: 'Stem Borer', name: 'Stem & Pink Borer' },
  { id: 'Weeds', name: 'Broadleaf & Grass Weeds' },
]

export const CATEGORIES = ['All', 'Fungicide', 'Insecticide', 'Bio-Stimulant', 'Herbicide', 'Nematicide']

// Product rows in the database still carry the original ./assets/pN.png paths,
// which are 1024x1024 JPEGs of roughly 430KB each. The .webp copies beside them
// are the same pictures at the size they are actually displayed, ~12KB. Map the
// bundled defaults across as they are rendered so stored rows get the small
// file without a data migration; anything else (a CMS upload, a remote URL) is
// passed through untouched.
export const FALLBACK_PRODUCT_IMAGE = '/assets/p1.webp'

export function productImage(product) {
  let src = String((product && product.image) || '').trim()
  // Uploads saved as an empty "data:image/png;base64," are not images.
  if (!src || /^data:image\/[\w+.-]+;base64,?$/i.test(src)) src = FALLBACK_PRODUCT_IMAGE
  return src.replace(/^\.\/assets\/(p[1-4])\.png$/, '/assets/$1.webp').replace(/^\.\/assets\//, '/assets/')
}

// Any product or basket image that fails to load shows the placeholder instead
// of broken-image alt text.
export function useFallbackImage(event) {
  const img = event.currentTarget
  if (img.dataset.fallbackApplied) return
  img.dataset.fallbackApplied = '1'
  img.src = FALLBACK_PRODUCT_IMAGE
}

const IMG = {
  fungicide: '/assets/p1.webp',
  insecticide: '/assets/p2.webp',
  biostim: '/assets/p3.webp',
  herbicide: '/assets/p4.webp',
}

export const PESTICIDES = [
  {
    id: 'sb-01',
    name: 'Sathya Bio BlastShield 75 WP',
    tagline: 'Systemic Bio-Fungicide for Paddy Blast & Neck Rot',
    category: 'Fungicide',
    crops: ['Paddy/Rice', 'Wheat', 'Corn'],
    diseases: ['Blast', 'Rust', 'Downy Mildew'],
    activeIngredient: 'Tricyclazole 75% WP + Bio-Enzyme Fortifier',
    dosage: '120g - 150g per Acre',
    packSizes: ['250g', '500g', '1kg'],
    selectedPack: '500g',
    safetyRating: 'Class III (Eco Friendly)',
    description: 'Advanced systemic bio-fortified fungicide providing protective and curative control against Blast disease in Paddy, Leaf Rust in Wheat, and Neck Blast.',
    detailedDescription: 'Sathya Bio BlastShield 75 WP is a highly specialized systemic fungicide tailored to combat the most stubborn fungal pathogens affecting grain crops. It rapidly penetrates the plant tissue, establishing a protective barrier that stops fungal spore germination and mycelial growth.',
    benefits: [
      'Rapid systemic action offering up to 15 days of protection.',
      'Prevents secondary infections and reduces neck rot incidence.',
      'Enhances grain quality and ensures higher milling yield.',
      'Rainfast within 2 hours of application.',
    ],
    modeOfAction: 'Inhibits melanin biosynthesis in appressoria, preventing the fungus from penetrating the plant cuticle.',
    applicationInstructions: 'Foliar spray at early symptoms or initiation of tillering phase. Dissolve 120g in 150L water per acre.',
    rating: 4.9,
    reviewsCount: 142,
    inStock: true,
    badge: 'Best Seller',
    image: IMG.fungicide,
    price: 680,
    originalPrice: 850,
    discount: '20% OFF',
  },
  {
    id: 'sb-02',
    name: 'Sathya Bio FlyKill Ultra',
    tagline: 'Multi-Action Insecticide for Whitefly & Aphids',
    category: 'Insecticide',
    crops: ['Cotton', 'Tomato', 'Citrus', 'Potato'],
    diseases: ['Whitefly', 'Aphids', 'Caterpillars'],
    activeIngredient: 'Diafenthiuron 50% WP + Botanical Neem Extract',
    dosage: '250g per Acre',
    packSizes: ['250g', '500g'],
    selectedPack: '250g',
    safetyRating: 'Class II (Bee Safe)',
    description: 'Penetrates leaf cuticle rapidly to paralyze sucking pests like Whiteflies, Aphids, and Thrips. Prevents leaf curl virus spread.',
    detailedDescription: 'FlyKill Ultra combines the fast knock-down power of modern chemistry with the sustained repellency of botanical neem extracts. It is highly effective against nymphs and adult stages of sucking pests.',
    benefits: [
      'Translaminar action kills pests hiding on the underside of leaves.',
      'Vapour action ensures broad coverage in dense crop canopies.',
      'Safe for beneficial insects like ladybird beetles.',
      'Phytotonic effect leaves crop greener.',
    ],
    modeOfAction: 'Inhibits mitochondrial respiration in insects, causing immediate paralysis.',
    applicationInstructions: 'Ensure thorough coverage of under-side of leaves. Spray early morning or post-sunset.',
    rating: 4.8,
    reviewsCount: 98,
    inStock: true,
    badge: 'Top Rated',
    image: IMG.insecticide,
    price: 840,
    originalPrice: 1050,
    discount: '20% OFF',
  },
  {
    id: 'sb-03',
    name: 'Sathya Bio BlightStop Pro',
    tagline: 'Dual Action Systemic Fungicide for Blight Control',
    category: 'Fungicide',
    crops: ['Tomato', 'Potato', 'Grapes', 'Citrus'],
    diseases: ['Blight', 'Downy Mildew'],
    activeIngredient: 'Mancozeb 64% + Metalaxyl 8% WP',
    dosage: '500g per Acre',
    packSizes: ['500g', '1kg', '5kg'],
    selectedPack: '1kg',
    safetyRating: 'Class III Low Toxicity',
    description: 'Gold standard dual-action fungicide specifically formulated for Late Blight in Potato/Tomato and Downy Mildew in Grapevines.',
    detailedDescription: 'BlightStop Pro provides unparalleled protection through a two-pronged approach: Mancozeb forms a protective film on the plant surface to prevent spore germination, while Metalaxyl is rapidly absorbed.',
    benefits: [
      'Curative and protective action prevents disease outbreaks.',
      'Excellent rainfastness and prolonged residual activity.',
      'Provides essential Manganese and Zinc micronutrients.',
    ],
    modeOfAction: 'Mancozeb acts as a multi-site contact inhibitor, while Metalaxyl inhibits protein synthesis within fungal pathogens.',
    applicationInstructions: 'Spray before rains or high moisture periods. Safe for crop canopy when used as directed.',
    rating: 4.9,
    reviewsCount: 215,
    inStock: true,
    badge: 'Expert Choice',
    image: IMG.fungicide,
    price: 750,
    originalPrice: 900,
    discount: '17% OFF',
  },
  {
    id: 'sb-04',
    name: 'Sathya Bio RootVigor Gold',
    tagline: '100% Organic Bio-Stimulant & Root Enhancer',
    category: 'Bio-Stimulant',
    crops: ['Paddy/Rice', 'Wheat', 'Cotton', 'Sugarcane', 'Corn', 'Tomato', 'Grapes'],
    diseases: [],
    activeIngredient: 'Humic Acid 18% + Seaweed Extract (Ascophyllum nodosum)',
    dosage: '500ml per Acre',
    packSizes: ['500ml', '1 Litre', '5 Litres'],
    selectedPack: '1 Litre',
    safetyRating: '100% Organic Certified',
    description: 'Accelerates root branching, enhances micro-nutrient absorption, and restores degraded soils. Boosts drought resilience.',
    detailedDescription: 'RootVigor Gold stimulates white feeder root growth and increases soil cation exchange capacity (CEC). It contains natural auxins, cytokinins, and trace minerals.',
    benefits: [
      'Enhances fertilizer utilization efficiency by 25-30%.',
      'Increases white root biomass for better anchoring and nutrient uptake.',
      'Improves drought and heat stress tolerance.',
    ],
    modeOfAction: 'Stimulates root cell division and chelates bound soil nutrients into plant-absorbable forms.',
    applicationInstructions: 'Apply through drip irrigation or drench around crop root zone during early growth stages.',
    rating: 4.9,
    reviewsCount: 310,
    inStock: true,
    badge: '100% Organic',
    image: IMG.biostim,
    price: 990,
    originalPrice: 1250,
    discount: '21% OFF',
  },
  {
    id: 'sb-26',
    name: 'Sathya Bio WeedClear 24-D',
    tagline: 'Systemic Broadleaf Herbicide',
    category: 'Herbicide',
    crops: ['Wheat', 'Corn', 'Sugarcane'],
    diseases: ['Weeds'],
    activeIngredient: '2,4-D Amine Salt 58% SL',
    dosage: '400ml per Acre',
    packSizes: ['400ml', '1 Litre', '5 Litres'],
    selectedPack: '1 Litre',
    safetyRating: 'Class II (Moderate)',
    description: 'Effective and economical post-emergence herbicide for the control of broadleaf weeds in cereals and sugarcane.',
    detailedDescription: 'WeedClear 24-D is a highly systemic herbicide that mimics the action of plant growth hormone auxin, causing uncontrolled growth in susceptible broadleaf weeds.',
    benefits: [
      'Excellent control of tough broadleaf weeds.',
      'Highly selective and safe for grass crops like wheat and sugarcane.',
      'Systemic action ensures complete kill from leaves to roots.',
    ],
    modeOfAction: 'Acts as a synthetic auxin, causing rapid, uncontrolled cell division and growth.',
    applicationInstructions: 'Apply as a foliar spray 30-35 days after sowing when weeds are in 2-4 leaf stage.',
    rating: 4.6,
    reviewsCount: 156,
    inStock: true,
    badge: 'Broadleaf Killer',
    image: IMG.herbicide,
    price: 340,
    originalPrice: 400,
    discount: '15% OFF',
  },
  {
    id: 'sb-27',
    name: 'Sathya Bio AminoBoost Liquid',
    tagline: 'Advanced Amino Acid Bio-Stimulant',
    category: 'Bio-Stimulant',
    crops: ['Tomato', 'Cotton', 'Grapes', 'Citrus', 'Paddy/Rice'],
    diseases: [],
    activeIngredient: 'L-Amino Acids 20% + Seaweed Extract',
    dosage: '250ml per Acre',
    packSizes: ['250ml', '500ml', '1 Litre'],
    selectedPack: '500ml',
    safetyRating: '100% Organic',
    description: 'A powerful anti-stress bio-stimulant that helps crops recover from weather, transplant, and chemical stress.',
    detailedDescription: 'AminoBoost provides plants with ready-made L-amino acids, saving the energy required for their synthesis. This energy is redirected towards growth and flowering.',
    benefits: [
      'Rapidly relieves plant stress from drought, heat, or phytotoxicity.',
      'Enhances pollen germination and fruit set.',
      'Improves efficacy of tank-mixed sprays.',
    ],
    modeOfAction: 'Provides direct precursors for protein synthesis and regulates stomatal opening.',
    applicationInstructions: 'Foliar spray during vegetative growth, pre-flowering, and fruit setting stages.',
    rating: 4.9,
    reviewsCount: 212,
    inStock: true,
    badge: 'Stress Reliever',
    image: IMG.biostim,
    price: 460,
    originalPrice: 550,
    discount: '16% OFF',
  },
  {
    id: 'sb-28',
    name: 'Sathya Bio NeemGuard 10000 PPM',
    tagline: 'Pure Cold-Pressed Bio-Insecticide & Antifeedant',
    category: 'Insecticide',
    crops: ['Paddy/Rice', 'Cotton', 'Tomato', 'Grapes', 'Citrus'],
    diseases: ['Aphids', 'Whitefly', 'Caterpillars'],
    activeIngredient: 'Azadirachtin 1% (10000 PPM) EC',
    dosage: '300ml per Acre',
    packSizes: ['250ml', '500ml', '1 Litre'],
    selectedPack: '500ml',
    safetyRating: '100% Organic Certified',
    description: 'High-potency botanical neem formulation disrupting insect lifecycle, feeding, and egglaying without chemical residues.',
    detailedDescription: 'Sathya Bio NeemGuard 10000 PPM is extracted using high-grade cold-press technology to preserve active Azadirachtin. It acts as an antifeedant, repellent, and insect growth regulator.',
    benefits: [
      'Zero pre-harvest interval - completely safe for organic & export crops.',
      'Inhibits pest resistance development when mixed with chemical sprays.',
      'Safe for beneficial insects.',
    ],
    modeOfAction: 'Disrupts ecdysone hormone systems, preventing molting and suppressing feeding.',
    applicationInstructions: 'Foliar spray at 3ml per Litre water. Apply early morning or evening.',
    rating: 4.9,
    reviewsCount: 184,
    inStock: true,
    badge: '100% Organic',
    image: IMG.insecticide,
    price: 580,
    originalPrice: 720,
    discount: '19% OFF',
  },
  {
    id: 'sb-29',
    name: 'Sathya Bio CopperShield 50 WG',
    tagline: 'Water Dispersible Bio-Bactericide & Contact Fungicide',
    category: 'Fungicide',
    crops: ['Tomato', 'Potato', 'Grapes', 'Citrus'],
    diseases: ['Blight', 'Downy Mildew'],
    activeIngredient: 'Copper Hydroxide 50% WG',
    dosage: '400g per Acre',
    packSizes: ['250g', '500g', '1kg'],
    selectedPack: '500g',
    safetyRating: 'Class III (Eco Friendly)',
    description: 'Advanced WG formulation offering broad-spectrum protective defense against bacterial spot, late blight, and downy mildew.',
    detailedDescription: 'CopperShield 50 WG releases micro-fine copper ions that stick tightly to plant foliage, preventing bacterial and fungal spore germination.',
    benefits: [
      'Disperses instantly in water without clogging nozzles.',
      'Protects foliage against both bacterial spot and fungal blights.',
      'High tenacity & superior rain-fast performance.',
    ],
    modeOfAction: 'Copper ions denature cellular proteins and enzymes in fungal spores and bacterial cell walls.',
    applicationInstructions: 'Mix 2g per Litre water. Apply preventively when disease weather is forecast.',
    rating: 4.7,
    reviewsCount: 129,
    inStock: true,
    badge: 'Bactericide Guard',
    image: IMG.fungicide,
    price: 620,
    originalPrice: 750,
    discount: '17% OFF',
  },
  {
    id: 'sb-30',
    name: 'Sathya Bio SulphaStar 80 WDG',
    tagline: 'Micronutrient Fortified Powdery Mildew & Mite Guard',
    category: 'Fungicide',
    crops: ['Grapes', 'Wheat', 'Sugarcane', 'Citrus'],
    diseases: ['Downy Mildew', 'Rust'],
    activeIngredient: 'Sulphur 80% WDG',
    dosage: '1kg per Acre',
    packSizes: ['1kg', '3kg', '5kg'],
    selectedPack: '1kg',
    safetyRating: 'Class III (Eco Safe)',
    description: 'Dual-action micronutrient fertilizer and contact fungicide for controlling powdery mildew, rust, and red spider mites.',
    detailedDescription: 'SulphaStar 80 WDG delivers elemental sulphur in instantly wettable micro-granules. It satisfies plant sulphur deficiency while creating a hostile environment for mildew spores.',
    benefits: [
      'Boosts chlorophyll formation, oil synthesis, and protein levels.',
      'Controls powdery mildew & spider mites simultaneously.',
      'Granular non-dusty WDG formulation.',
    ],
    modeOfAction: 'Vapour phase oxidation disrupts fungal respiratory chain and mite cell membranes.',
    applicationInstructions: 'Dissolve 2.5g per Litre water. Spray at first sign of powdery mildew.',
    rating: 4.8,
    reviewsCount: 167,
    inStock: true,
    badge: 'Powdery Mildew Care',
    image: IMG.fungicide,
    price: 390,
    originalPrice: 480,
    discount: '18% OFF',
  },
  {
    id: 'sb-31',
    name: 'Sathya Bio StemKill 18.5 SC',
    tagline: 'Broad Spectrum Stem Borer & Leaf Folder Specialist',
    category: 'Insecticide',
    crops: ['Paddy/Rice', 'Sugarcane', 'Corn'],
    diseases: ['Stem Borer', 'Caterpillars'],
    activeIngredient: 'Chlorantraniliprole 18.5% SC',
    dosage: '60ml per Acre',
    packSizes: ['60ml', '150ml'],
    selectedPack: '60ml',
    safetyRating: 'Class III Low Toxicity',
    description: 'Ultra-concentrated systemic insecticide providing extended control of stem borer, leaf folder, and bollworms.',
    detailedDescription: 'StemKill 18.5 SC is absorbed rapidly by plant tissue and translocated throughout stems and leaves to protect tillers.',
    benefits: [
      'Long duration protection - up to 21 days single application.',
      'Prevents dead heart formation and white earheads in paddy.',
      'Preserves beneficial spiders in fields.',
    ],
    modeOfAction: 'Activates insect ryanodine receptors, causing muscle contraction and feeding cessation.',
    applicationInstructions: 'Apply 60ml per acre in 150L water at 20-30 days post transplanting.',
    rating: 4.9,
    reviewsCount: 280,
    inStock: true,
    badge: 'Top Seller',
    image: IMG.insecticide,
    price: 890,
    originalPrice: 1100,
    discount: '19% OFF',
  },
  {
    id: 'sb-32',
    name: 'Sathya Bio BloomMax Super',
    tagline: 'Flower Booster & Fruit Drop Prevention Bio-Stimulant',
    category: 'Bio-Stimulant',
    crops: ['Tomato', 'Cotton', 'Grapes', 'Citrus'],
    diseases: [],
    activeIngredient: 'Nitrobenzene 20% + Boron & Zinc Chelates',
    dosage: '250ml per Acre',
    packSizes: ['250ml', '500ml', '1 Litre'],
    selectedPack: '500ml',
    safetyRating: '100% Non-Toxic',
    description: 'Plant flowering stimulant engineered to trigger abundant flower initiation, prevent flower drop, and enlarge fruit size.',
    detailedDescription: 'BloomMax Super regulates flower-inducing hormones and provides critical micronutrients like Boron and Zinc.',
    benefits: [
      'Increases flower cluster count by up to 35%.',
      'Drastically reduces flower and young fruit drop under heat stress.',
      'Improves fruit color and market price.',
    ],
    modeOfAction: 'Stimulates plant flowering hormones and enhances carbohydrate translocation.',
    applicationInstructions: 'Foliar application at pre-flowering stage and repeat 15 days later.',
    rating: 4.9,
    reviewsCount: 195,
    inStock: true,
    badge: 'Yield Booster',
    image: IMG.biostim,
    price: 520,
    originalPrice: 650,
    discount: '20% OFF',
  },
  {
    id: 'sb-33',
    name: 'Sathya Bio GrassOut 10 EC',
    tagline: 'Selective Post-Emergence Grass Weed Herbicide',
    category: 'Herbicide',
    crops: ['Cotton', 'Tomato', 'Potato', 'Sugarcane'],
    diseases: ['Weeds'],
    activeIngredient: 'Quizalofop-ethyl 10% EC',
    dosage: '300ml per Acre',
    packSizes: ['250ml', '500ml', '1 Litre'],
    selectedPack: '500ml',
    safetyRating: 'Class II (Selective)',
    description: 'Systemic selective herbicide for complete control of annual and perennial grass weeds in broadleaf crops.',
    detailedDescription: 'GrassOut 10 EC targets narrow-leaf grass weeds infesting cotton, tomato, and potato crops without damaging the main crop.',
    benefits: [
      'Highly selective - zero damage to broadleaf crops like cotton & tomato.',
      'Kills tough perennial grasses like Cynodon dactylon.',
      'Rain-fast within 1 hour.',
    ],
    modeOfAction: 'Inhibits acetyl-CoA carboxylase (ACCase) enzyme in grass weeds.',
    applicationInstructions: 'Spray when grass weeds are at 2-4 leaf stage.',
    rating: 4.7,
    reviewsCount: 110,
    inStock: true,
    badge: 'Grass Eliminator',
    image: IMG.herbicide,
    price: 480,
    originalPrice: 580,
    discount: '17% OFF',
  },
  {
    id: 'sb-34',
    name: 'Sathya Bio Trichoderma Viride 1% WP',
    tagline: 'Bio-Control Soil Fungicide for Root Rot & Wilt',
    category: 'Fungicide',
    crops: ['Paddy/Rice', 'Cotton', 'Tomato', 'Sugarcane', 'Grapes'],
    diseases: ['Blight', 'Rust'],
    activeIngredient: 'Trichoderma Viride (Min 2 x 10^8 CFU/g)',
    dosage: '1kg per Acre',
    packSizes: ['1kg', '5kg'],
    selectedPack: '1kg',
    safetyRating: '100% Organic Certified',
    description: 'Antagonistic biological fungicide that parasitizes root rot, collar rot, and Fusarium wilt pathogens in soil.',
    detailedDescription: 'Trichoderma Viride is a beneficial bio-fungal culture that colonizes root zones and destroys soil fungal pathogens.',
    benefits: [
      'Controls seed-borne and soil-borne fungal diseases organically.',
      'Promotes dense root system.',
      'Restores soil biological balance.',
    ],
    modeOfAction: 'Hyperparasitism, antibiosis, and competition around root surfaces.',
    applicationInstructions: 'Mix 1kg with 100kg farmyard manure and incorporate into moist soil.',
    rating: 4.9,
    reviewsCount: 240,
    inStock: true,
    badge: 'Bio-Fungicide',
    image: IMG.fungicide,
    price: 290,
    originalPrice: 380,
    discount: '23% OFF',
  },
  {
    id: 'sb-35',
    name: 'Sathya Bio Pseudomonas 1% WP',
    tagline: 'Bio-Bactericide & Systemic Induced Resistance Activator',
    category: 'Fungicide',
    crops: ['Paddy/Rice', 'Tomato', 'Potato', 'Citrus', 'Wheat'],
    diseases: ['Blight', 'Blast'],
    activeIngredient: 'Pseudomonas fluorescens (Min 2 x 10^8 CFU/g)',
    dosage: '1kg per Acre',
    packSizes: ['1kg', '5kg'],
    selectedPack: '1kg',
    safetyRating: '100% Organic Certified',
    description: 'Potent bio-agent protecting crops against bacterial leaf blight, sheath rot, and damping off.',
    detailedDescription: 'Pseudomonas fluorescens produces siderophores that starve soil pathogens of iron while inducing systemic plant resistance.',
    benefits: [
      'Dual action: bio-bactericide + plant growth promoting rhizobacteria.',
      'Boosts crop vigor and suppresses leaf streak.',
      'Safe for organic farming.',
    ],
    modeOfAction: 'Siderophore iron chelation and production of phenazine antibiotics.',
    applicationInstructions: 'Foliar spray at 10g per Litre water or root drenching.',
    rating: 4.8,
    reviewsCount: 175,
    inStock: true,
    badge: 'Bacterial Guard',
    image: IMG.fungicide,
    price: 310,
    originalPrice: 400,
    discount: '22% OFF',
  },
]

export const SAMPLE_DISEASE_DIAGNOSES = [
  {
    keyword: 'blight',
    diseaseName: 'Early / Late Blight',
    cropDetected: 'Tomato / Potato',
    confidence: '96.4%',
    symptoms: 'Dark brown concentric rings on lower leaves.',
    recommendedProduct: 'Sathya Bio BlightStop Pro (500g/acre)',
    productId: 'sb-03',
  },
]

export const WHATSAPP_EXPERT_URL = 'https://wa.me/919442562423?text=Hello%20Sathya%20Bio%20Expert%2C%20I%20need%20crop%20advice'

export const rupees = value => `₹${Number(value || 0).toLocaleString('en-IN')}`
